package actuators

const (
	CHANNEL_HEAD_SERVO = 0

	CHANNEL_HAND_1 = 1
	CHANNEL_HAND_2 = 2
	CHANNEL_HAND_3 = 3

	// last F: Far, C: Close
	CHANNEL_KNEE_SERVO_FRF = 4
	CHANNEL_KNEE_SERVO_FRC = 5
	CHANNEL_KNEE_SERVO_FLF = 6
	CHANNEL_KNEE_SERVO_FLC = 7
	CHANNEL_KNEE_SERVO_BRF = 8
	CHANNEL_KNEE_SERVO_BRC = 9
	CHANNEL_KNEE_SERVO_BLF = 10
	CHANNEL_KNEE_SERVO_BLC = 11

	CHANNEL_WHEEL_FR = 12
	CHANNEL_WHEEL_FL = 13
	CHANNEL_WHEEL_BR = 14
	CHANNEL_WHEEL_BL = 15
)
